### ISSUE TITLE
薪资模块修改

### ISSUE THREAD

**Issue by Last-Order-Wsk** [huajian-pro/resume-design#205]
薪资部分没有自定义或者面议的选择吗
<img width="377" alt="image" src="https://user-images.githubusercontent.com/73875874/200781001-dcdcc901-6980-4d61-9552-c124f710fe3d.png">

**Comment by Hacker233** [comment]
已添加该功能：薪资模块 可以选择 面议或自定义。

**Comment by Hacker233** [comment]
![image](https://user-images.githubusercontent.com/28037169/201078640-d841464f-933a-4f62-9b8a-2ac31b506202.png)
